source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'KSCrash', '~> 0.0.3'
pod 'MKNetworkKit', '~> 0.87'
pod 'RegexKitLite', '~> 4.0'
pod 'ZBarSDK', '~> 1.3.1'
pod 'Bitheri', :git => 'git@github.com:bither/bitheri.git', :branch => 'develop'