source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'KSCrash', '~> 0.0.3'
pod 'MKNetworkKit', '~> 0.87'
pod "AFNetworking", "~> 2.0"
pod 'RegexKitLite', '~> 4.0'
pod 'SimpleKeychain'
pod 'FXBlurView'
pod 'OpenSSL', :git => 'https://github.com/bither/OpenSSL.git', :branch => 'master'
pod 'Bitheri', :git => 'https://github.com/bither/bitheri.git', :branch => 'develop'