platform :ios, '7.0'
pod 'KSCrash', '~> 0.0.3'
pod 'MKNetworkKit', '~> 0.87'
pod 'RegexKitLite', '~> 4.0'
pod 'ZBarSDK', '~> 1.3.1'
pod 'Bitheri', :git => 'git@gitlab.com:bither/bitheri.git', :branch => 'develop'